services:
  db:
    image: "postgres:latest"
    env_file: ./.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node/app

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 15433:80
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db
  #   # networks:
  #   #   - postgres-network
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin/

volumes:
  postgres-data: {}
  pgadmin-data: {}
